CREATE DATABASE userapp_db;
USE userapp_db;
CREATE TABLE users
(
 id INT AUTO_INCREMENT,
 NAME VARCHAR(20) NOT NULL,
 email_id VARCHAR(20) NOT NULL,
 PASSWORD VARCHAR(20) NOT NULL,
 active TINYINT(1) NOT NULL DEFAULT 1,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 modified_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 CONSTRAINT pk_users_id PRIMARY KEY(id),
 CONSTRAINT uk_users_email_id UNIQUE(email_id)
 );
 
 
 